name: steganography_app_indiv
description: Консольное приложение для стеганографии с синдромным вложением на основе кодов Хэмминга
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  crypto: ^3.0.7
  image: ^4.5.4
  args: ^2.5.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  coverage: ^1.10.0
